### ISSUE TITLE
setup-vlang-action@v1 is completely unusable

### ISSUE THREAD

**Issue by alexesprit** [nocturlab/setup-vlang-action#84]
...for installing recent V versions. But it should be a preferred way to use `v1` tag instead of `master`.

I see two options to keep compatibility with all V versions.

1. Check both URLs (with `v` and with no `v` prefix in the filename), and use fist valid URL.
2. Don't rely on prebuilt archives, and download source code manually (e.g. https://github.com/vlang/v/archive/0.2.1.zip). It won't work for `latest` version (?), but this is not an issue (latest prebuilt archives contain `v` prefix in their names, so we don't need to keep compatibility now).
3. Use GitHub API and fetch list of attached files for the release. It should be easy to get platform-specific archive from that list.

**Comment by shiipou** [comment]
> setup-vlang-action@v1 is completely unusable for installing recent V versions. But it should be a preferred way to use `v1` tag instead of `master`.

Oups I just forgot to validate the tag. It was currently a Draft Release so the workflow didn't linked it to v1.
I will probably set weekly tests to use the tag, instead of checkout of the repository to alert me on this types of mistakes.

> I see two options to keep compatibility with all V versions.
> 
>     1. Check both URLs (with `v` and with no `v` prefix in the filename), and use fist valid URL.

All Releases without the `v_` prefix have been deleted by the Vlang Team. Now all release have zip name like this `v_<plateform>.zip (e.g: v_linux.zip) . Only releases before 0.1.20 have only source archive zip. I don't think they will change it. Because of the automated workflow.

>     2. Don't rely on prebuilt archives, and download source code manually (e.g. https://github.com/vlang/v/archive/0.2.1.zip). It won't work for `latest` version (?), but this is not an issue (latest prebuilt archives contain `v` prefix in their names, so we don't need to keep compatibility now).

You think it's better to use the source insead of the prebuild archive ?
I thought the opposite, but you probably have more experiences than me in open-sources projects.

>     3. Use GitHub API and fetch list of attached files for the release. It should be easy to get platform-specific archive from that list.

Yes, It can be better to use GitHub API to find the best file to download.

**Comment by shiipou** [comment]
@alexesprit Can you check that v1 work for you like master did ?

**Comment by alexesprit** [comment]
> Can you check that now v1 work for you like master did ?

Yes, it works fine now. Thanks!
